<?php

namespace ServerStatusBundle\Repository;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerStatusRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return null|object
     */
    public function getStatus()
    {
        return $this->find(1);
    }
}
