stages:
  - production

production_deploy:
  environment:
    name: production
    url: https://young-shelf-87369.herokuapp.com
  stage: production
  script:
    - gem install dpl
    - dpl --provider=heroku --app=young-shelf-87369 --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
    - master