stages:
  - staging
  - production

production_deploy:
  environment:
    name: production
    url: https://cards-production.herokuapp.com
  stage: production
  script:
    - gem install dpl
    - dpl --provider=heroku --app=cards-production --api-key=$HEROKU_API_KEY
  only:
    - master

# on test staging deploy
staging_deploy:
  environment:
    name: staging
    url: https://cards-staging.herokuapp.com
  stage: staging
  script:
    - gem install dpl
    - dpl --provider=heroku --app=cards-staging --api-key=$HEROKU_API_KEY
  only:
    - branches
  except:
    - master