stages:
  - production

production_deploy:
  environment:
    name: production
    url: https://cards-production.herokuapp.com
  stage: production
  script:
    - gem install dpl
    - dpl --provider=heroku --app=cards-production --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
    - master