nelmio_cors:
    paths:
        '^/api':
            allow_credentials: true
            allow_origin: ['^http://localhost:[0-9]+', '*']
            allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization', 'Origin', 'X-Requested-With', 'Accept']
            allow_methods: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE', 'OPTIONS']
            expose_headers: []
            max_age: 3600