framework:
    workflows:
        card_state:
            type: 'workflow'
            marking_store:
                type: 'single_state'
                arguments:
                    - 'status'
            supports:
                - ApiBundle\Entity\Card
            places:
                - backlog
                - todo
                - in_progress
                - done
                - closed
            transitions:
                start_todo:
                    from: backlog
                    to: todo
                start_progress:
                    from: todo
                    to: in_progress
                stop_progress:
                    from: in_progress
                    to: todo
                complete:
                    from: in_progress
                    to: done
                close:
                    from: done
                    to: closed
                reject:
                    from: done
                    to: in_progress