api:
    resource: "@ApiBundle/Controller/"
    type:     rest
    prefix:   api
    options:
        expose: true

app.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc
