# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        token_user_provider:
            id: auth.user_provider.token
        email_user_provider:
            id: auth.user_provider.email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        password_secure:
            pattern: '^/user/login'
            anonymous: false
            stateless: true
            guard:
                provider: email_user_provider
                authenticators:
                    - user.authenticator.password

        token_secure:
            pattern: '^/'
            anonymous: true
            stateless: true
            guard:
                provider: token_user_provider
                authenticators:
                    - auth.authenticator.token

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
        ROLE_USER:
            - ROLE_RESTRICTED

    access_control:
        - { path: '^/admin', roles: 'ROLE_ADMIN' }
