services:
    json.decoder:
      class: ApiBundle\Decoder\JsonDecoder

    card.manager:
      class: ApiBundle\Manager\CardManager
      arguments:
           - '@doctrine.orm.entity_manager'
           - '@validator'

    personal_data.voter:
      class: ApiBundle\Security\Voter\PersonalDataVoter
      arguments:
           - '@security.access.decision_manager'
      tags: [ security.voter ]


    content.param_converter.merging:
        class: ApiBundle\Serializer\ParamConverter\MergingRequestBodyParamConverter
        arguments:
            - "@fos_rest.converter.request_body"
            - "@doctrine"
        tags:
            - { name: request.param_converter, converter: merging, priority: -50 }

    statusable.listener:
        class: ApiBundle\EventHandler\StatusableListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }