UserBundle\Entity\User:
    exclusion_policy: all
    access_type: public_method
    read_only: false
    callback_methods:
        pre_serialize: [preSerialize]
    properties:
        id:
            access_type: property
            groups:
                - user_list
                - user_detail
                - card_list
                - card_detail
            expose: true
        username:
            groups:
                - user_create
                - user_update
                - user_list
                - user_signup
                - user_detail
                - card_list
                - card_detail
            expose: true
        name:
            groups:
                - user_create
                - user_update
                - user_list
                - user_detail
                - card_list
                - card_detail
            expose: true
        email:
            groups:
                - user_create
                - user_list
                - user_detail
                - user_signup
            expose: true
        passwordPlain:
            groups:
                - user_create
                - user_updateo
                - user_signup
            type: string
            expose: true
        roles:
            groups:
                - user_create
                - user_update
                - user_list
                - user_detail
                - user_signup
            type: array
            expose: true
            read_only: false
        token:
            groups:
                - user_detail
            expose: true
            read_only: true
